# Generated by Django 3.2.4 on 2021-06-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
